X chain removal from Cross-Chain tab #4
OneByte-Technologies/flare-staking-tool pull request #4
Opened 2023-08-24 07:22 UTC by Kun-J

Removed the option of 'X" chain from the components below:
1. Source Chain
2. Destination Chain
3. Address card
4. Any text/description for the same

2023-08-25 06:38 UTC, mishramonalisha76 approved these changes

2023-08-25 12:40 UTC, avinash-onebyte requested changes

2023-08-25 12:40 UTC, avinash-onebyte commented on src/store/modules/network/constants.ts
> +    'https://flare-api.flare.network/ext/C/rpc'.
change to dot to comma after rpc

2023-08-26 05:44 UTC, Kun-J commented on src/store/modules/network/constants.ts
> +    'https://flare-api.flare.network/ext/C/rpc'.
Done

2023-08-28 07:43 UTC, merged